"""Interactive setup wizard for first-run MarlinSpike deployments.

v3.5.2 changed the boot semantics: ``create_app()`` now refuses to start
without ``SECRET_KEY`` and ``DATABASE_URL`` set explicitly (previous
behaviour silently generated an ephemeral session key and shipped a
default DB credential — both footguns). This wizard fills the gap by
walking a first-time operator through generating those values into a
``.env`` file with restrictive permissions.

CLI::

    marlinspike-setup           # interactive — prompts for choices
    marlinspike-setup --auto    # non-interactive — generate everything

Defaults err on the side of "secure first, ergonomic second":

* SECRET_KEY        — generated, 64 hex chars
* DATABASE_URL      — defaults to a SQLite file under data/ for dev;
                      operator can paste a postgres URL instead
* ADMIN_PASSWORD    — generated, displayed once at end of wizard
* SESSION_COOKIE_SECURE — defaults to true; opt-out flag for dev
* MARLINSPIKE_RESET_TOKEN_DELIVERY — defaults to ``file``
* MARLINSPIKE_CAPTURE_REQUIRE — defaults to ``admin``

The wizard never overwrites an existing ``.env`` without ``--force``.
"""

from __future__ import annotations

import argparse
import os
import secrets
import string
import sys
from pathlib import Path

ENV_PATH_DEFAULT = Path(".env")


def _gen_secret_hex(n: int = 32) -> str:
    return secrets.token_hex(n)


def _gen_password(n: int = 24) -> str:
    """Generate a strong password with mixed alphabet, no quote chars."""
    alphabet = string.ascii_letters + string.digits + "!#$%&*+-=?@^_~"
    return "".join(secrets.choice(alphabet) for _ in range(n))


def _prompt(label: str, default: str = "", auto: bool = False) -> str:
    if auto:
        return default
    suffix = f" [{default}]" if default else ""
    try:
        value = input(f"{label}{suffix}: ").strip()
    except EOFError:
        value = ""
    return value or default


def _prompt_yes_no(label: str, default: bool = True, auto: bool = False) -> bool:
    if auto:
        return default
    default_str = "Y/n" if default else "y/N"
    try:
        value = input(f"{label} [{default_str}]: ").strip().lower()
    except EOFError:
        value = ""
    if not value:
        return default
    return value in ("y", "yes")


def _existing_env(path: Path) -> dict[str, str]:
    """Parse a flat .env file into a dict. Comments and blank lines ignored."""
    if not path.is_file():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def _write_env(path: Path, kv: dict[str, str]) -> None:
    """Write a .env file with restrictive permissions (0600)."""
    body_lines = []
    body_lines.append("# Generated by marlinspike-setup. Permissions: 0600.")
    body_lines.append("# Do not commit this file. Rotate SECRET_KEY + DB password if it leaks.")
    body_lines.append("")
    for k, v in kv.items():
        body_lines.append(f"{k}={v}")
    body_lines.append("")
    body = "\n".join(body_lines)
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as f:
        f.write(body)


def _print_banner():
    print("=" * 60)
    print("  MarlinSpike — first-run setup")
    print("=" * 60)
    print()


def _print_summary(env: dict[str, str], env_path: Path):
    print()
    print("=" * 60)
    print("  Setup complete")
    print("=" * 60)
    print(f"  .env written: {env_path.resolve()} (mode 0600)")
    print(f"  DATABASE_URL: {_redact(env.get('DATABASE_URL', ''))}")
    print("  SECRET_KEY:   <generated, 64 hex chars>")
    if env.get("ADMIN_PASSWORD"):
        print()
        print("  ADMIN BOOTSTRAP CREDENTIAL")
        print("  username: admin")
        print(f"  password: {env['ADMIN_PASSWORD']}")
        print("  Change this immediately after first login.")
    print()
    print("  Next steps:")
    print("    1. source the env into your shell:")
    print("         export $(grep -v '^#' .env | xargs)")
    print("    2. start the app:")
    print("         python -m marlinspike.app")
    print("       or with Docker:")
    print("         docker compose up -d --build")
    print("=" * 60)


def _redact(url: str) -> str:
    """Hide passwords in postgres-style URLs for the summary printout."""
    if not url or "://" not in url:
        return url
    scheme, rest = url.split("://", 1)
    if "@" not in rest:
        return url
    creds, host = rest.rsplit("@", 1)
    if ":" in creds:
        user = creds.split(":", 1)[0]
        return f"{scheme}://{user}:***@{host}"
    return url


def run(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="marlinspike-setup",
        description="Bootstrap MarlinSpike for first run (.env file generation).",
    )
    parser.add_argument(
        "--auto",
        action="store_true",
        help="Non-interactive mode — accept all defaults, no prompts.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing .env file. Default: refuse.",
    )
    parser.add_argument(
        "--env-path",
        default=str(ENV_PATH_DEFAULT),
        help="Path to .env file (default: ./.env).",
    )
    parser.add_argument(
        "--print-only",
        action="store_true",
        help="Print the generated values to stdout instead of writing a file.",
    )
    args = parser.parse_args(argv)

    env_path = Path(args.env_path)

    if env_path.exists() and not args.force and not args.print_only:
        print(
            f"refusing to overwrite existing {env_path}; pass --force or "
            f"--print-only to override.",
            file=sys.stderr,
        )
        return 1

    _print_banner()

    existing = _existing_env(env_path) if env_path.exists() else {}

    # SECRET_KEY — always generate fresh unless an existing one is present
    secret_key = existing.get("SECRET_KEY") or _gen_secret_hex(32)

    # DATABASE_URL — prompt unless --auto
    default_db = existing.get("DATABASE_URL") or "sqlite:///./data/marlinspike.db"
    if args.auto:
        database_url = default_db
    else:
        print("DATABASE_URL")
        print("  Default: SQLite file under data/ (suitable for single-host dev).")
        print("  For production: postgresql://user:STRONG_PASS@host:5432/marlinspike")
        database_url = _prompt("DATABASE_URL", default=default_db, auto=False)

    # ADMIN_PASSWORD — generate
    admin_password = existing.get("ADMIN_PASSWORD") or _gen_password()

    # Session cookie security
    if args.auto:
        session_secure = True
    else:
        print()
        print("SESSION_COOKIE_SECURE")
        print("  Set to true for production (TLS). false for plain-HTTP dev only.")
        session_secure = _prompt_yes_no(
            "Enable secure cookies?", default=True, auto=False
        )

    # Reset token delivery
    if args.auto:
        reset_delivery = "file"
    else:
        print()
        print("MARLINSPIKE_RESET_TOKEN_DELIVERY")
        print("  'disabled' (operator only — admin resets via DB)")
        print("  'file' (token written to data/instance/reset-tokens/, mode 0600)")
        print("  'log' (token printed to server stderr)")
        reset_delivery = _prompt(
            "Reset token delivery", default="file", auto=False
        )
        if reset_delivery not in ("disabled", "file", "log"):
            reset_delivery = "file"

    # Capture control
    if args.auto:
        capture_require = "admin"
    else:
        print()
        print("MARLINSPIKE_CAPTURE_REQUIRE")
        print("  'admin' — only admins can start/stop live capture (recommended)")
        print("  'any'   — any logged-in user can")
        capture_require = _prompt(
            "Capture-control role", default="admin", auto=False
        )
        if capture_require not in ("admin", "any"):
            capture_require = "admin"

    env = {
        "SECRET_KEY": secret_key,
        "DATABASE_URL": database_url,
        "ADMIN_PASSWORD": admin_password,
        "SESSION_COOKIE_SECURE": "true" if session_secure else "false",
        "MARLINSPIKE_RESET_TOKEN_DELIVERY": reset_delivery,
        "MARLINSPIKE_CAPTURE_REQUIRE": capture_require,
    }

    if args.print_only:
        for k, v in env.items():
            print(f"{k}={v}")
        return 0

    _write_env(env_path, env)
    _print_summary(env, env_path)
    return 0


def main(argv: list[str] | None = None) -> int:
    return run(argv)


if __name__ == "__main__":
    sys.exit(main())
